version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
    links:
      - "db"
    environment:
      - MONGODB_HOST=db
